/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    guidesSidebar: [{ type: 'autogenerated', dirName: 'guides' }],
    // By default, Docusaurus generates a sidebar from the docs folder structure
    guidesSidebar: [
        'guides/index',
        {
            type: 'category',
            label: 'Basics',
            collapsed: true,
            items: [
                'guides/basics/what-pixijs-is',
                'guides/basics/what-pixijs-is-not',
                'guides/basics/getting-started',
                'guides/basics/architecture-overview',
                'guides/basics/render-loop',
                'guides/basics/scene-graph',
                'guides/basics/svg',
            ],
        },
        {
            type: 'category',
            label: 'Advanced',
            collapsed: true,
            items: [
                'guides/advanced/render-groups',
                'guides/advanced/cache-as-texture',
                'guides/advanced/mixing-three-and-pixi',
                'guides/advanced/render-layers',
            ],
        },
        {
            type: 'category',
            label: 'Components',
            collapsed: true,
            items: [
                'guides/components/assets',
                'guides/components/containers',
                {
                    type: 'category',
                    label: 'Graphics',
                    collapsed: true,
                    items: [
                        'guides/components/graphics',
                        'guides/components/graphics-pixel-line',
                        'guides/components/graphics-fill',
                    ],
                },
                'guides/components/interaction',
                'guides/components/sprites',
                'guides/components/sprite-sheets',
                'guides/components/text',
                'guides/components/textures',
            ],
        },
        {
            type: 'category',
            label: 'Production',
            collapsed: true,
            items: ['guides/production/performance-tips'],
        },
        {
            type: 'category',
            label: 'Migrations',
            collapsed: true,
            items: ['guides/migrations/v8', 'guides/migrations/v7', 'guides/migrations/v6', 'guides/migrations/v5'],
        },
    ],

    examplesSidebar: [{ type: 'autogenerated', dirName: 'examples' }],

    // TODO: add docs back in
    // apiSidebar: [{ type: 'autogenerated', dirName: 'api' }],

    // But you can create a sidebar manually
    /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
