// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  guidesSidebar: [{ type: 'autogenerated', dirName: 'guides' }],
};

module.exports = sidebars;
