name: PR

on: [ pull_request ]

jobs:
  pr:
    name: PR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
      - run: npm ci
      - run: npm run types
      - run: npm run lint
