name: PR

on: [pull_request]

jobs:
    pr:
        name: PR
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '18'
                  cache: 'npm'
            - run: npm ci
            - run: npm run types
            - run: npm run lint
