name: Reusable Deploy

on:
  workflow-call:
    secrets:
      GITHUB_TOKEN:
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - run: npm ci

      - run: npm run types

      - run: npm run lint

      - run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          npm run deploy
        env:
          GIT_USER: $GITHUB_ACTOR
          GIT_PASS: ${{ secrets.GITHUB_TOKEN }}
