name: Pixi Dev Update
on:
  repository_dispatch:
    types: [ update-dev ]
jobs:
  update-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm ci

      - name: write new pixi-versions.json
        run: npm run write-versions -- ${{ github.event.client_payload.sha }}

      - name: setup git config
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
        env:
          GIT_USER: $GITHUB_ACTOR
          GIT_PASS: ${{ secrets.GITHUB_TOKEN }}

      - name: commit
        run: |
          git add pixi-versions.json
          git commit -m "new pixi-versions.json built from pixijs/pixijs: ${{ github.event.client_payload.ref }} merge commit: ${{ github.event.client_payload.pr_sha }} using CodeSandbox CI build: ${{ github.event.client_payload.sha }}"
          git push origin main

  call-deploy:
    uses: ./.github/workflows/reusable-deploy.yml
    secrets: inherit


